### ISSUE TITLE
( ViewTube ) The setting button is not working well

### ISSUE THREAD

**Issue by XAMIR555** [mauriceoegerli/ViewTube#1]
#### Project Information
* Repository-----------: [Here](https://github.com/mauriceoegerli/ViewTube)
* Project Name---------:  [ViewTube](https://viewtube.eu/)
* Publisher------------:[ Maurice Oegerli](https://github.com/mauriceoegerli)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I click on the Settings button, all options in the Settings button should be opened

#### Actual behavior

When I click on the Settings button, no options appear  And the settings button does not give me any response

#### How to reproduce
* go to https://viewtube.eu/
*  Click on the Settings button at the top right side
* Note the Bug
*  1 Browser  version : Firefox  60.0.3 60.6.3esr (32-bit) 
*   2 Browser  version -:  google chrome version 74.0.3729.112
* Operating system----: Dell E5530 core i5 
* computer generation--: 4th

#### Recording Of The Bug
![20190511_015442](https://user-images.githubusercontent.com/49812927/57556953-46334b00-732d-11e9-8908-514d3eefbe8c.gif)

**Comment by XAMIR555** [comment]
Sir @mauriceoegerli review my post please

**Comment by moisout** [comment]
Settings button has been temporarily removed, until settings page is available. Thank you for your help.

**Comment by XAMIR555** [comment]
ok sir thanks u
